kind: ConfigMap
apiVersion: v1
metadata:
  name: simplespring-config
data:
  application-dev.yaml: |-
    spring:
      config:
        activate:
          on-profile: dev
    environment: development
    greeting: hello from ConfigMap dev
    foo: bar
  application-prod.yaml: |-
    spring:
      config:
        activate:
          on-profile: prod
    environment: production
    greeting: hello from ConfigMap prod
    foo: bazz