apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
    service: grafana
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: grafana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana
        volumeMounts:
        - name: grafana-provisioning-datasources
          mountPath: /etc/grafana/provisioning/datasources
        env:
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: "Admin"
        - name: GF_AUTH_DISABLE_LOGIN_FORM
          value: "true"
        ports:
        - containerPort: 3000
      volumes:
      - name: grafana-provisioning-datasources
        configMap:
          name: grafana-provisioning-datasources
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning-datasources
data:
  datasources.yml: |
    apiVersion: 1
    datasources:
    - name: Zipkin
      type: zipkin
      uid: zipkin
      url: http://zipkin:9411
      basicAuth: false
      isDefault: false      