apiVersion: v1
kind: Service
metadata:
  name: simplespring
  labels:
    app: simplespring
    service: simplespring
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: simplespring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplespring
  labels:
    app: simplespring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simplespring
  template:
    metadata:
      labels:
        app: simplespring
    spec:
      containers:
      - name: simplespring
        image: docker.io/gustphitchaya/simplespring:d724832bcb2ef9e2e8bf10a26f02ab0ff89da562
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        volumeMounts:
        - name: config-volume
          mountPath: /config
      volumes:
      - name: config-volume
        configMap:
          name: simplespring-config