apiVersion: v1
kind: Service
metadata:
  name: config-server
  labels:
    app: config-server
    service: config-server
spec:
  ports:
  - port: 8888
    name: http
  selector:
    app: config-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  labels:
    app: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: docker.io/gustphitchaya/cloud-config-server
        ports:
        - containerPort: 8888
