apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplespring
  labels:
    app: simplespring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simplespring
  template:
    metadata:
      labels:
        app: simplespring
    spec:
      containers:
      - name: simplespring
        image: docker.io/gustphitchaya/simplespring:7150bb7342fed39b91890f8f94012107b20f8dcc
        ports:
        - containerPort: 8080