name: Create and publish a Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  image: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/simplespring:${{ github.sha }}

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up JDK 17 for armv7
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and push Docker image
        run: |
          mvn compile jib:build \
            -Djib.to.image=${{ env.image }}

  # azure-aci-deploy:
  #   needs: docker-build-push
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: 'Login via Azure CLI'
  #       uses: azure/login@v2
  #       with:
  #         creds: ${{ secrets.AZURE_CREDENTIALS }}

  #     - name: Deploy on ACI
  #       uses: Azure/cli@v2
  #       with:
  #         azcliversion: latest
  #         inlineScript: |
  #           az container create -g Learn --name simplespring --image ${{ env.image }} --ports 8080 --ip-address Public
